version: '3'

services:
  api:
    build: api/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: api

  interface:
    build: interface/
    depends_on:
      - api
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: interface

networks:
  deploy_network:
    driver: bridge